

name: barcodeRaspi

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq python-wxgtk3.0
        python -m pip install --upgrade pip
        pip install pytest pytest-cov freezegun gitpython pandas
    - name: Test with pytest
      run: |
        pytest -vv --cov=./ --cov-config=.coveragerc --cov-report=xml:coverage.xml ./tests/
